<html>

<head title="fault tolerant of Promise All, even with JSON">

</head>

<body>
    <div id="root"> Full name:
        <input type="text" id="userNameInput" disabled="true" />
    </div>

    <script>
        let alert = console.log;
        class HttpError extends Error {
            constructor(response) {
                super(`${response.status} for ${response.url}`);
                this.name = 'HttpError';
                this.response = response;
            }
        }

        async function loadJson(url) {
            let response = await fetch(url);
            if (response.status == 200)
                return response.json();
            else
                throw new HttpError(response);
        }

        // Ask for a user name until github returns a valid user
        async function demoGithubUser() {
            let name = "jxjjligang";
            try {
                let user = await loadJson(`https://api.github.com/users/${name}`);

                alert(`Full name: ${user.name}.`);
                userNameInput.value = user.name;
                return user;
            }
            catch (err) {
                if (err instanceof HttpError && err.response.status == 404) {
                    alert("No such user, please reenter.");
                    // return demoGithubUser();
                } else {
                    throw err;
                }
            };
        }

        demoGithubUser();
        console.log(`Code behind async function will run first, without waiting it to complete.`);

    </script>
</body>

</html>